### ISSUE TITLE
[Docs] Add more docs about metrics description

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger-website#11]
Right now the website only contains the Chinese documentation of OpenDigger metric.

We should add docs for all the metrics listed in the introduction https://open-digger.cn/en/docs/user_docs/intro 

The original issue could be found in https://github.com/X-lab2017/open-digger/issues?q=is%3Aissue+Metrics+in%3Atitle

And there is an example in our old website: https://x-lab2017.github.io/open-digger/#/metrics/technical_fork

The metrics description should be placed under https://open-digger.cn/en/docs/user_docs/metrics/how_to_use

We can add both English and Chinese version with English content in the first place and translate the docs later

**Comment by Neilblaze** [comment]
@frank-zsy Linking to [#7](https://github.com/X-lab2017/open-digger-website/issues/13#issuecomment-2112410120), before moving forward, I'm curious to know where I can get access to "*all the metrics*" (since you mentioned), where all I can see is "Indicator usage guide" 

![image](https://github.com/X-lab2017/open-digger-website/assets/48355572/6ef26cf2-6c4c-4c9d-b08e-a8e967aa3263)

I'd love to have a chat with you to get things on the same plate asap.

**Comment by Neilblaze** [comment]
Oh, I get it now. Also, I'm curious to know, do we have a list of codepen (example) links that I can use to tap into (as of now) ?

**Comment by frank-zsy** [comment]
Yes, in the introduction documentation, you can find CodePen demo URL in each row of the metrics.

**Comment by Neilblaze** [comment]
Thanks, I'll take a look!

**Comment by Neilblaze** [comment]
Just confirming, #11 is linked with [#1183](https://github.com/X-lab2017/open-digger/issues/1183), correct?

**Comment by frank-zsy** [comment]
Yes, actually it is for the old version website, but still valid for this repo.
